// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.EmailValidator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("creationDate")]
        public object CreationDate { get; set; }

        [JsonProperty("domain")]
        public string Domain { get; set; }

        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("username")]
        public string Username { get; set; }

        [JsonProperty("canConnect")]
        public bool CanConnect { get; set; }

        [JsonProperty("hasTypo")]
        public bool HasTypo { get; set; }

        [JsonProperty("isValid")]
        public bool IsValid { get; set; }

        [JsonProperty("isMxValid")]
        public bool IsMxValid { get; set; }

        [JsonProperty("isSmtpValid")]
        public bool IsSmtpValid { get; set; }

        [JsonProperty("isRegexValid")]
        public bool IsRegexValid { get; set; }

        [JsonProperty("smtp")]
        public Smtp Smtp { get; set; }

        [JsonProperty("isCompanyEmail")]
        public bool IsCompanyEmail { get; set; }

        [JsonProperty("isFreeEmail")]
        public bool IsFreeEmail { get; set; }

        [JsonProperty("checksum")]
        public long Checksum { get; set; }
    }

    public partial class Smtp
    {
        [JsonProperty("valid")]
        public bool Valid { get; set; }

        [JsonProperty("reason")]
        public string Reason { get; set; }
    }
}
