// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.EmailValidator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("domain")]
        public string Domain { get; set; }

        [JsonProperty("username")]
        public string Username { get; set; }

        [JsonProperty("isRegexValid")]
        public bool? IsRegexValid { get; set; }

        [JsonProperty("hasTypo")]
        public bool? HasTypo { get; set; }

        [JsonProperty("isMxValid")]
        public bool? IsMxValid { get; set; }

        [JsonProperty("isValid")]
        public bool? IsValid { get; set; }

        [JsonProperty("isFreeEmail")]
        public bool? IsFreeEmail { get; set; }

        [JsonProperty("isCompanyEmail")]
        public bool? IsCompanyEmail { get; set; }

        [JsonProperty("isDisposable")]
        public bool? IsDisposable { get; set; }

        [JsonProperty("isRoleAccount")]
        public bool? IsRoleAccount { get; set; }

        [JsonProperty("suggestedCorrection")]
        public object SuggestedCorrection { get; set; }

        [JsonProperty("riskScore")]
        public long? RiskScore { get; set; }

        [JsonProperty("riskLevel")]
        public string RiskLevel { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
